version: "3.9"
services:
  welcome-to-dubai-php:
    build:
      context: .
      args:
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
      dockerfile: ./docker/php/Dockerfile
    container_name: welcome-to-dubai-php
    networks:
      welcome-to-dubai:
        ipv4_address: ${SUBNET}.2
    volumes:
      - "./docker/php/etc/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./docker/php/logs/:/var/log/php-fpm/"
      - "./docker/php/lock:/lock/"
      - "./:/var/www/html/welcome-to-dubai/"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - XDEBUG_SESSION=${XDEBUG_SESSION}
      - ENDPOINT=${ENDPOINT}
      - ROOT_FOLDER=${ROOT_FOLDER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    extra_hosts:
      - "${NGINX_HOST_SERVER}:${SUBNET}.4"
    depends_on:
      - welcome-to-dubai-db
  welcome-to-dubai-db:
    image: postgres:latest
    container_name: welcome-to-dubai-db
    ports:
      - "${PGSQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    networks:
      welcome-to-dubai:
        ipv4_address: ${SUBNET}.3
    volumes:
      - ./docker/pgsql/data:/var/lib/postgresql/data
      - ./docker/pgsql/init:/docker-entrypoint-initdb.d
  welcome-to-dubai-web:
    image: nginx:alpine
    container_name: welcome-to-dubai-web
    volumes:
      - "./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/conf/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./:/var/www/html/welcome-to-dubai"
      - "./docker/nginx/logs/access.log:/var/logs/nginx/access.log"
      - "./docker/nginx/logs/error.log:/var/logs/nginx/error.log"
      - "./docker/nginx/etc/ssl:/etc/ssl"
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      - NGINX_HOST_SERVER=${NGINX_HOST_SERVER}
    networks:
      welcome-to-dubai:
        ipv4_address: ${SUBNET}.4
    command: /bin/sh -c "envsubst '$$NGINX_HOST_SERVER $$NGINX_HOST_CLIENT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - welcome-to-dubai-php
networks:
  welcome-to-dubai:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}.0/28
